import type { Node } from "../App";

export const optimus: Node = {
  id: "eb2ce10d-4c0b-4d86-bb2e-c46417e2b799",
  name: "Optimus",
  type: "group",
  opacity: 1,
  translateX: 600,
  translateY: 512,
  translateZ: 144,
  scaleX: 0.88,
  scaleY: 1,
  scaleZ: 1,
  rotateX: 0,
  rotateY: 0,
  rotateZ: 180,
  width: 200,
  height: 200,
  depth: 200,
  radius: 150,
  baseSides: 3,
  collapsed: false,
  children: [
    {
      id: "8a82f2c0-7d46-444b-92ef-c04c766b571c",
      name: "Head center",
      type: "group",
      color: "#dbdbdb",
      opacity: 1,
      translateX: 100,
      translateY: 0,
      translateZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 200,
      depth: 200,
      radius: 200,
      baseSides: 3,
      collapsed: true,
      children: [
        {
          id: "35786528-8e38-428a-81a3-c0574d622f53",
          name: "mouthguard",
          type: "prism",
          opacity: 1,
          translateX: 0,
          translateY: -50,
          translateZ: 4,
          scaleX: 0.8,
          scaleY: 0.8,
          scaleZ: 0.8,
          rotateX: 6,
          rotateY: 0,
          rotateZ: 30,
          width: 200,
          height: 199,
          depth: 200,
          radius: 200,
          baseSides: 6,
          children: [],
        },
        {
          id: "985b68ca-7eb7-487b-a002-ccdd5f22858b",
          name: "inner head",
          type: "prism",
          opacity: 1,
          translateX: 0,
          translateY: 9,
          translateZ: 126,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 30,
          width: 200,
          height: 130,
          depth: 200,
          radius: 155,
          baseSides: 6,
          children: [],
        },
        {
          id: "2355957b-b712-42c1-9007-42f0f1df34f7",
          name: "New cuboid",
          type: "cuboid",
          opacity: 1,
          translateX: 0,
          translateY: -64,
          translateZ: 92,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: -9,
          rotateY: 0,
          rotateZ: 0,
          width: 60,
          height: 202,
          depth: 75,
          radius: 200,
          baseSides: 3,
          children: [],
        },
        {
          id: "9cfcdfda-4d8c-4035-b2e6-28108b17450a",
          name: "New prism",
          type: "prism",
          color: "#39c6d0",
          opacity: 1,
          translateX: 81,
          translateY: -108,
          translateZ: 112,
          scaleX: 1,
          scaleY: 1.44,
          scaleZ: 1,
          rotateX: 90,
          rotateY: 213,
          rotateZ: 266,
          width: 200,
          height: 5,
          depth: 200,
          radius: 34,
          baseSides: 5,
          children: [],
        },
        {
          id: "297e00df-d5d2-476d-8821-43265658a3d1",
          name: "New prism clone",
          type: "prism",
          color: "#39c6d0",
          opacity: 1,
          translateX: -81,
          translateY: -108,
          translateZ: 112,
          scaleX: 1,
          scaleY: 1.44,
          scaleZ: 1,
          rotateX: 93,
          rotateY: 152,
          rotateZ: 274,
          width: 200,
          height: 5,
          depth: 200,
          radius: 34,
          baseSides: 5,
          children: [],
        },
      ],
    },
    {
      id: "8c05cb8c-4ab3-41b6-a787-160da3ba412d",
      name: "Helmet",
      type: "group",
      color: "#203ED5",
      opacity: 1,
      translateX: 100,
      translateY: 0,
      translateZ: 0,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 200,
      depth: 200,
      radius: 200,
      baseSides: 3,
      collapsed: true,
      children: [
        {
          id: "9ca35147-68d0-4661-a72f-ab7ef713491f",
          name: "brow",
          type: "prism",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: 177,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 6,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 78,
          depth: 200,
          radius: 200,
          baseSides: 8,
          children: [],
        },
        {
          id: "06fa4104-df82-477c-bc58-4ba34400bce3",
          name: "back",
          type: "prism",
          opacity: 1,
          translateX: 0,
          translateY: 74,
          translateZ: 48,
          scaleX: 1,
          scaleY: 0.82,
          scaleZ: 1,
          rotateX: 6,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 203,
          depth: 200,
          radius: 200,
          baseSides: 14,
          children: [],
        },
        {
          id: "9b8f23f7-1109-4892-9eee-f55bd19af61c",
          name: "dome",
          type: "prism",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: 215,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 78,
          depth: 200,
          radius: 170,
          baseSides: 14,
          children: [],
        },
        {
          id: "5667caa8-f280-426a-93fe-bafa53d330ee",
          name: "dome",
          type: "pyramid",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: 288,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 68,
          depth: 200,
          radius: 170,
          baseSides: 14,
          children: [],
        },
        {
          id: "c083a819-53e7-4cb4-9a00-434b18c9291a",
          name: "Crown",
          type: "group",
          opacity: 1,
          translateX: 0,
          translateY: 5,
          translateZ: 259,
          scaleX: 1,
          scaleY: 0.6,
          scaleZ: 1,
          rotateX: -2,
          rotateY: 0,
          rotateZ: 90,
          width: 200,
          height: 200,
          depth: 200,
          radius: 200,
          baseSides: 3,
          collapsed: true,
          children: [
            {
              id: "b997c8c5-8528-497c-8e75-05e9a6ea908d",
              name: "New prism",
              type: "prism",
              opacity: 1,
              translateX: 0,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 408,
              depth: 200,
              radius: 114,
              baseSides: 5,
              children: [],
            },
            {
              id: "7d2ef226-e40b-4168-92e5-a98160386c17",
              name: "New prism clone",
              type: "prism",
              color: "#dbdbdb",
              opacity: 1,
              translateX: -5,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 408,
              depth: 200,
              radius: 97,
              baseSides: 5,
              collapsed: true,
              children: [
                {
                  id: "dde7812c-d7c9-43c7-9e62-8ca7483f7356",
                  name: "New cuboid",
                  type: "cuboid",
                  color: "#4a4a4a",
                  opacity: 1,
                  translateX: -60,
                  translateY: 0,
                  translateZ: -204,
                  scaleX: 1,
                  scaleY: 1,
                  scaleZ: 1,
                  rotateX: 0,
                  rotateY: 0,
                  rotateZ: 0,
                  width: 5,
                  height: 122,
                  depth: 3,
                  radius: 200,
                  baseSides: 3,
                  children: [],
                },
                {
                  id: "62f8377b-5747-4616-9023-8d4f788ed6c4",
                  name: "New cuboid clone",
                  type: "cuboid",
                  color: "#4a4a4a",
                  opacity: 1,
                  translateX: -40,
                  translateY: 0,
                  translateZ: -204,
                  scaleX: 1,
                  scaleY: 1,
                  scaleZ: 1,
                  rotateX: 0,
                  rotateY: 0,
                  rotateZ: 0,
                  width: 5,
                  height: 133,
                  depth: 3,
                  radius: 200,
                  baseSides: 3,
                  children: [],
                },
                {
                  id: "98adfe6f-fb16-421b-9f03-d53eb6e620e2",
                  name: "New cuboid clone clone",
                  type: "cuboid",
                  color: "#4a4a4a",
                  opacity: 1,
                  translateX: -20,
                  translateY: 0,
                  translateZ: -204,
                  scaleX: 1,
                  scaleY: 1,
                  scaleZ: 1,
                  rotateX: 0,
                  rotateY: 0,
                  rotateZ: 0,
                  width: 5,
                  height: 147,
                  depth: 3,
                  radius: 200,
                  baseSides: 3,
                  children: [],
                },
                {
                  id: "d6b6de56-ddf9-4776-83e7-b5eaeaba1c67",
                  name: "New cuboid clone clone clone",
                  type: "cuboid",
                  color: "#4a4a4a",
                  opacity: 1,
                  translateX: 0,
                  translateY: 0,
                  translateZ: -204,
                  scaleX: 1,
                  scaleY: 1,
                  scaleZ: 1,
                  rotateX: 0,
                  rotateY: 0,
                  rotateZ: 0,
                  width: 5,
                  height: 160,
                  depth: 3,
                  radius: 200,
                  baseSides: 3,
                  children: [],
                },
                {
                  id: "e9b21529-b5c8-48ca-94a1-f4d9486e09cf",
                  name: "New cuboid clone clone clone clone",
                  type: "cuboid",
                  color: "#4a4a4a",
                  opacity: 1,
                  translateX: 20,
                  translateY: 0,
                  translateZ: -204,
                  scaleX: 1,
                  scaleY: 1,
                  scaleZ: 1,
                  rotateX: 0,
                  rotateY: 0,
                  rotateZ: 0,
                  width: 5,
                  height: 174,
                  depth: 3,
                  radius: 200,
                  baseSides: 3,
                  children: [],
                },
                {
                  id: "69f4acd2-3adf-44f0-b57e-9e52766f3345",
                  name: "New cuboid clone clone clone clone clone",
                  type: "cuboid",
                  color: "#4a4a4a",
                  opacity: 1,
                  translateX: 40,
                  translateY: 0,
                  translateZ: -204,
                  scaleX: 1,
                  scaleY: 1,
                  scaleZ: 1,
                  rotateX: 0,
                  rotateY: 0,
                  rotateZ: 0,
                  width: 5,
                  height: 139,
                  depth: 3,
                  radius: 200,
                  baseSides: 3,
                  children: [],
                },
                {
                  id: "f45890c7-a8c1-4ad6-ac86-84ec04d8fb3c",
                  name: "New cuboid clone clone clone clone clone clone",
                  type: "cuboid",
                  color: "#4a4a4a",
                  opacity: 1,
                  translateX: 60,
                  translateY: 0,
                  translateZ: -204,
                  scaleX: 1,
                  scaleY: 1,
                  scaleZ: 1,
                  rotateX: 0,
                  rotateY: 0,
                  rotateZ: 0,
                  width: 5,
                  height: 85,
                  depth: 3,
                  radius: 200,
                  baseSides: 3,
                  children: [],
                },
                {
                  id: "fd1962c0-c692-44a6-83d8-ed6370a04fc7",
                  name: "New cuboid clone clone clone clone clone clone clone",
                  type: "cuboid",
                  color: "#4a4a4a",
                  opacity: 1,
                  translateX: 80,
                  translateY: 0,
                  translateZ: -204,
                  scaleX: 1,
                  scaleY: 1,
                  scaleZ: 1,
                  rotateX: 0,
                  rotateY: 0,
                  rotateZ: 0,
                  width: 5,
                  height: 34,
                  depth: 3,
                  radius: 200,
                  baseSides: 3,
                  children: [],
                },
              ],
            },
          ],
        },
        {
          id: "2737ebba-fede-4a14-bda5-b141ca17d08e",
          name: "left side",
          type: "group",
          opacity: 1,
          translateX: 192,
          translateY: 20,
          translateZ: 74,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 200,
          depth: 200,
          radius: 200,
          baseSides: 3,
          collapsed: true,
          children: [
            {
              id: "694bf8eb-41bc-4ac9-bbd2-bf6197cc3619",
              name: "New pyramid",
              type: "pyramid",
              opacity: 1,
              translateX: 30,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 60,
              depth: 200,
              radius: 176,
              baseSides: 8,
              children: [],
            },
            {
              id: "e8bbe001-0645-40a6-9282-4e4177294018",
              name: "New cuboid",
              type: "cuboid",
              opacity: 1,
              translateX: -30,
              translateY: -80,
              translateZ: -70,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 8,
              rotateY: 0,
              rotateZ: -9,
              width: 60,
              height: 232,
              depth: 166,
              radius: 200,
              baseSides: 3,
              children: [],
            },
            {
              id: "45c84006-d165-4f9b-bde3-95e923235056",
              name: "New cuboid clone",
              type: "cuboid",
              color: "#bdad00",
              opacity: 1,
              translateX: -30,
              translateY: -88,
              translateZ: -70,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 8,
              rotateY: 0,
              rotateZ: -9,
              width: 44,
              height: 227,
              depth: 132,
              radius: 200,
              baseSides: 3,
              children: [],
            },
            {
              id: "a4cbfae2-1106-4357-9d6a-1d4e5b3e03cc",
              name: "New prism",
              type: "prism",
              opacity: 1,
              translateX: 47,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 32,
              depth: 200,
              radius: 75,
              baseSides: 16,
              children: [],
            },
            {
              id: "c18d1a86-1170-4101-a5c1-ce0db925e6b8",
              name: "New prism clone",
              type: "prism",
              color: "#dbdbdb",
              opacity: 1,
              translateX: 51,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 32,
              depth: 200,
              radius: 57,
              baseSides: 16,
              children: [],
            },
            {
              id: "e8d2aaeb-1f67-4b33-9f6a-f914d492a413",
              name: "New prism clone clone",
              type: "prism",
              color: "#808080",
              opacity: 1,
              translateX: 60,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 32,
              depth: 200,
              radius: 40,
              baseSides: 16,
              children: [],
            },
            {
              id: "41810672-0905-4f7b-aea6-8dfd95670ae6",
              name: "antenna",
              type: "prism",
              opacity: 1,
              translateX: 40,
              translateY: 0,
              translateZ: 162,
              scaleX: 1,
              scaleY: 0.21,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 265,
              rotateZ: 0,
              width: 200,
              height: 20,
              depth: 200,
              radius: 200,
              baseSides: 3,
              children: [],
            },
          ],
        },
        {
          id: "b074610e-76a8-4726-898e-d8fb4b5c83c9",
          name: "right side",
          type: "group",
          opacity: 1,
          translateX: -192,
          translateY: 20,
          translateZ: 74,
          scaleX: -1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 200,
          depth: 200,
          radius: 200,
          baseSides: 3,
          collapsed: false,
          children: [
            {
              id: "6a888e5c-641e-4f12-96bf-3e73e15c8ed7",
              name: "New pyramid",
              type: "pyramid",
              opacity: 1,
              translateX: 30,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 60,
              depth: 200,
              radius: 176,
              baseSides: 8,
              children: [],
            },
            {
              id: "f642b7c0-1561-4947-ba37-5986cb802e5e",
              name: "New cuboid",
              type: "cuboid",
              opacity: 1,
              translateX: -30,
              translateY: -80,
              translateZ: -70,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 8,
              rotateY: 0,
              rotateZ: -9,
              width: 60,
              height: 232,
              depth: 166,
              radius: 200,
              baseSides: 3,
              children: [],
            },
            {
              id: "c44023db-a6ca-41a1-9cbc-bc59af1e4a54",
              name: "New cuboid clone",
              type: "cuboid",
              color: "#bdad00",
              opacity: 1,
              translateX: -30,
              translateY: -88,
              translateZ: -70,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 8,
              rotateY: 0,
              rotateZ: -9,
              width: 44,
              height: 227,
              depth: 132,
              radius: 200,
              baseSides: 3,
              children: [],
            },
            {
              id: "f5e0acc6-fd6f-4bbe-a860-76d55e5d44b5",
              name: "New prism",
              type: "prism",
              opacity: 1,
              translateX: 47,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 32,
              depth: 200,
              radius: 75,
              baseSides: 16,
              children: [],
            },
            {
              id: "cd4bf709-5de6-4dbf-a2fd-bb3e253b57a6",
              name: "New prism clone",
              type: "prism",
              color: "#dbdbdb",
              opacity: 1,
              translateX: 51,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 32,
              depth: 200,
              radius: 57,
              baseSides: 16,
              children: [],
            },
            {
              id: "e4f325fd-1edb-427f-802a-ca9c739f0866",
              name: "New prism clone clone",
              type: "prism",
              color: "#808080",
              opacity: 1,
              translateX: 60,
              translateY: 0,
              translateZ: 0,
              scaleX: 1,
              scaleY: 1,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 90,
              rotateZ: 0,
              width: 200,
              height: 32,
              depth: 200,
              radius: 40,
              baseSides: 16,
              children: [],
            },
            {
              id: "43cd20fc-cf2d-4035-a3d5-f848fe874a44",
              name: "antenna",
              type: "prism",
              opacity: 1,
              translateX: 40,
              translateY: 0,
              translateZ: 162,
              scaleX: 1,
              scaleY: 0.21,
              scaleZ: 1,
              rotateX: 0,
              rotateY: 265,
              rotateZ: 0,
              width: 200,
              height: 20,
              depth: 200,
              radius: 200,
              baseSides: 3,
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
