import type { Node } from "../App";

export const snowman: Node[] = [
  {
    id: "e2de6042-3567-42c6-9398-981ff3716985",
    name: "Snowman",
    type: "group",
    children: [
      {
        id: "3831c9c5-36c1-4c9c-b1a9-06b6551c01a8",
        name: "bottom",
        type: "sphere",
        collapsed: true,
        children: [
          {
            id: "3016ad39-7f98-4f13-a7d6-96d91b22ac9d",
            name: "button",
            type: "cuboid",
            children: [],
            color: "#000000",
            opacity: 1,
            translateX: 169,
            translateY: -4,
            translateZ: 44,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            rotateX: 55,
            rotateY: 41,
            rotateZ: 0,
            width: 23,
            height: 21,
            depth: 24,
            radius: 178,
            baseSides: 3,
          },
          {
            id: "4eab67f4-8917-433d-9eac-7476a215327c",
            name: "button ",
            type: "cuboid",
            children: [],
            color: "#000000",
            opacity: 1,
            translateX: 123,
            translateY: -4,
            translateZ: 117,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            rotateX: 20,
            rotateY: 41,
            rotateZ: 33,
            width: 23,
            height: 21,
            depth: 24,
            radius: 200,
            baseSides: 3,
          },
        ],
        opacity: 1,
        translateX: 0,
        translateY: 0,
        translateZ: 0,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 0.88,
        rotateX: 0,
        rotateY: 6,
        rotateZ: 0,
        width: 200,
        height: 200,
        depth: 200,
        radius: 178,
        baseSides: 3,
      },
      {
        id: "35fc2efa-d8fc-485d-b5a4-e463e8cc229c",
        name: "middle",
        type: "sphere",
        collapsed: true,
        children: [
          {
            id: "8513301b-802c-4474-a41c-509ba944fac7",
            name: "button",
            type: "cuboid",
            children: [],
            color: "#000000",
            opacity: 1,
            translateX: 129,
            translateY: 3,
            translateZ: 33,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            rotateX: 14,
            rotateY: 62,
            rotateZ: 0,
            width: 22,
            height: 21,
            depth: 32,
            radius: 143,
            baseSides: 3,
          },
          {
            id: "0cf27d2b-88c0-4aea-b799-f3cc05587486",
            name: "button ",
            type: "cuboid",
            children: [],
            color: "#000000",
            opacity: 1,
            translateX: 129,
            translateY: 3,
            translateZ: -37,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            rotateX: -20,
            rotateY: 105,
            rotateZ: 0,
            width: 22,
            height: 21,
            depth: 32,
            radius: 200,
            baseSides: 3,
          },
        ],
        opacity: 1,
        translateX: -6,
        translateY: 0,
        translateZ: 193,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 0.86,
        rotateX: 0,
        rotateY: -7,
        rotateZ: 0,
        width: 200,
        height: 200,
        depth: 200,
        radius: 143,
        baseSides: 3,
      },
      {
        id: "8ab8ce0f-23fe-423a-9bf4-b3e66b3c74f6",
        name: "head+hat",
        collapsed: false,
        type: "group",
        children: [
          {
            id: "d3776dc3-44db-44f1-85d5-5e46aa3c9257",
            name: "head",
            type: "sphere",
            children: [
              {
                id: "b771b7ee-d0a2-4530-8612-a1bd079bb8ef",
                name: "eye",
                type: "cuboid",
                children: [],
                color: "#000000",
                opacity: 1,
                translateX: 73,
                translateY: 47,
                translateZ: 16,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: -13,
                rotateY: 0,
                rotateZ: 0,
                width: 21,
                height: 15,
                depth: 14,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "5845b2aa-aebb-48cd-8fcd-48df9d7f27d9",
                name: "eye",
                type: "cuboid",
                children: [],
                color: "#000000",
                opacity: 1,
                translateX: 75,
                translateY: -47,
                translateZ: 17,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: -104,
                rotateY: 4,
                rotateZ: 0,
                width: 23,
                height: 15,
                depth: 12,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "0d974475-8d4d-49c5-87ab-4f25cf43ae79",
                name: "mouth coal",
                type: "cuboid",
                children: [],
                color: "#000000",
                opacity: 1,
                translateX: 70,
                translateY: 52,
                translateZ: -31,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: -13,
                rotateY: 0,
                rotateZ: 0,
                width: 15,
                height: 13,
                depth: 11,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "5b622092-f08a-496d-802f-d4519f363775",
                name: "mouth coal",
                type: "cuboid",
                children: [],
                color: "#000000",
                opacity: 1,
                translateX: 77,
                translateY: 25,
                translateZ: -39,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: 55,
                rotateY: 14,
                rotateZ: 0,
                width: 15,
                height: 13,
                depth: 11,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "93e0a4d5-75ed-4fc4-9274-5513bcd10ed7",
                name: "mouth coal",
                type: "cuboid",
                children: [],
                color: "#000000",
                opacity: 1,
                translateX: 80,
                translateY: -2,
                translateZ: -42,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: -74,
                rotateY: 0,
                rotateZ: 0,
                width: 15,
                height: 13,
                depth: 11,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "011e644c-e3d4-4886-b7a6-3017af756884",
                name: "mouth coal",
                type: "cuboid",
                children: [],
                color: "#000000",
                opacity: 1,
                translateX: 75,
                translateY: -29,
                translateZ: -39,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: -74,
                rotateY: 55,
                rotateZ: 0,
                width: 15,
                height: 13,
                depth: 11,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "7acceff8-8de7-48a7-98e1-bbf2261235a2",
                name: "mouth coal",
                type: "cuboid",
                children: [],
                color: "#000000",
                opacity: 1,
                translateX: 73,
                translateY: -48,
                translateZ: -28,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: -74,
                rotateY: 55,
                rotateZ: 0,
                width: 10,
                height: 13,
                depth: 13,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "a55cf951-fc01-4e3d-8793-f56ac8bee5aa",
                name: "nose",
                type: "pyramid",
                children: [],
                color: "#ff8800",
                opacity: 1,
                translateX: 126,
                translateY: 0,
                translateZ: 0,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: 0,
                rotateY: 90,
                rotateZ: 0,
                width: 200,
                height: 100,
                depth: 200,
                radius: 20,
                baseSides: 7,
              },
            ],
            opacity: 1,
            translateX: 0,
            translateY: 0,
            translateZ: 0,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 0.91,
            rotateX: 0,
            rotateY: 0,
            rotateZ: 0,
            width: 200,
            height: 200,
            depth: 200,
            radius: 92,
            baseSides: 3,
          },
          {
            id: "20f65dc4-a66f-4393-a8a1-4208e9f6efa1",
            name: "hat",
            type: "prism",
            children: [
              {
                id: "b0ef32ba-285d-40f5-8779-9a5dee8b9339",
                name: "hat pipe",
                type: "prism",
                children: [],
                opacity: 1,
                translateX: 0,
                translateY: 0,
                translateZ: 68,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: 0,
                rotateY: 0,
                rotateZ: 0,
                width: 200,
                height: 149,
                depth: 200,
                radius: 72,
                baseSides: 14,
              },
              {
                id: "65f23c53-cc3b-4b1a-a4d2-9fc421469396",
                name: "hat rim",
                type: "prism",
                children: [],
                color: "#a80000",
                opacity: 1,
                translateX: 0,
                translateY: 0,
                translateZ: 18,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: 0,
                rotateY: 0,
                rotateZ: 0,
                width: 200,
                height: 33,
                depth: 200,
                radius: 75,
                baseSides: 14,
              },
              {
                id: "bfc32ad8-67a8-4fe1-acc3-1cbf8c2be6f1",
                name: "hat flare",
                type: "pyramid",
                children: [],
                opacity: 1,
                translateX: 0,
                translateY: 0,
                translateZ: 57,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: 0,
                rotateY: 180,
                rotateZ: 0,
                width: 200,
                height: 200,
                depth: 200,
                radius: 80,
                baseSides: 14,
              },
            ],
            color: "#2c2926",
            opacity: 1,
            translateX: -6,
            translateY: 6,
            translateZ: 53,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            rotateX: -2,
            rotateY: -7,
            rotateZ: 0,
            width: 200,
            height: 7,
            depth: 200,
            radius: 115,
            baseSides: 14,
          },
        ],
        opacity: 1,
        translateX: 0,
        translateY: 0,
        translateZ: 370,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        width: 200,
        height: 200,
        depth: 200,
        radius: 200,
        baseSides: 3,
      },
      {
        id: "a4413d31-d007-45f8-9343-d756d7d98d58",
        name: "scarf",
        collapsed: true,
        type: "prism",
        children: [
          {
            id: "9b2b5811-9ce6-4022-9910-052fe9677d12",
            name: "scarf segement",
            type: "cuboid",
            children: [
              {
                id: "68fc01e9-94d4-4fb3-aba2-76d91cdffc06",
                name: "scarf end",
                type: "cuboid",
                children: [],
                opacity: 1,
                translateX: 3,
                translateY: 43,
                translateZ: -65,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: 64,
                rotateY: 0,
                rotateZ: 0,
                width: 53,
                height: 14,
                depth: 103,
                radius: 200,
                baseSides: 3,
              },
            ],
            opacity: 1,
            translateX: 100,
            translateY: 60,
            translateZ: -4,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            rotateX: 45,
            rotateY: -36,
            rotateZ: 145,
            width: 53,
            height: 14,
            depth: 103,
            radius: 200,
            baseSides: 3,
          },
          {
            id: "1ab4eb5b-d1cc-4c35-860f-f4923b06906c",
            name: "scarf segement ",
            type: "cuboid",
            children: [
              {
                id: "4a9de29c-c6e1-4094-bed9-b15d069d6d36",
                name: "scarf end",
                type: "cuboid",
                children: [],
                opacity: 1,
                translateX: 3,
                translateY: 43,
                translateZ: -65,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: 64,
                rotateY: 0,
                rotateZ: 0,
                width: 53,
                height: 14,
                depth: 103,
                radius: 200,
                baseSides: 3,
              },
            ],
            opacity: 1,
            translateX: 78,
            translateY: 93,
            translateZ: -3,
            scaleX: 1,
            scaleY: 0.74,
            scaleZ: 0.76,
            rotateX: 57,
            rotateY: -16,
            rotateZ: 145,
            width: 53,
            height: 14,
            depth: 103,
            radius: 200,
            baseSides: 3,
          },
        ],
        color: "#156b0a",
        opacity: 1,
        translateX: 0,
        translateY: 0,
        translateZ: 284,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: 3,
        rotateY: 7,
        rotateZ: 0,
        width: 200,
        height: 64,
        depth: 200,
        radius: 94,
        baseSides: 14,
      },
      {
        id: "0a0e4047-ee26-411e-a304-9c1c2d0549ab",
        name: "left arm",
        type: "cuboid",
        collapsed: true,
        children: [
          {
            id: "ad0b566b-5151-4eb7-90f4-829ef95a794a",
            name: "forearm",
            type: "cuboid",
            children: [
              {
                id: "09e5c948-ed5d-4d9d-ac7a-3641e119f63a",
                name: "finger",
                type: "cuboid",
                children: [],
                opacity: 1,
                translateX: -2,
                translateY: 44,
                translateZ: -24,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: -53,
                rotateY: -27,
                rotateZ: 0,
                width: 7,
                height: 76,
                depth: 10,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "2dee4ee1-7dcb-4c8d-bb48-be48c529e5b7",
                name: "finger",
                type: "cuboid",
                children: [],
                opacity: 1,
                translateX: 8,
                translateY: 64,
                translateZ: 25,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: 59,
                rotateY: -27,
                rotateZ: -11,
                width: 7,
                height: 61,
                depth: 10,
                radius: 200,
                baseSides: 3,
              },
            ],
            opacity: 1,
            translateX: 0,
            translateY: 106,
            translateZ: 26,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            rotateX: 41,
            rotateY: 0,
            rotateZ: 0,
            width: 13,
            height: 100,
            depth: 13,
            radius: 200,
            baseSides: 3,
          },
        ],
        color: "#71480e",
        opacity: 1,
        translateX: 0,
        translateY: 160,
        translateZ: 249,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: 23,
        rotateY: 39,
        rotateZ: 0,
        width: 16,
        height: 150,
        depth: 12,
        radius: 200,
        baseSides: 3,
      },
      {
        id: "7911bc5a-15a7-4318-8e46-abc9297d204c",
        name: "right arm",
        collapsed: true,
        type: "cuboid",
        children: [
          {
            id: "469192f4-8fda-4f7a-a37c-161910bb9f5e",
            name: "forearm",
            type: "cuboid",
            children: [
              {
                id: "7f8e6fd9-433b-4a04-a37e-04a80f674402",
                name: "finger",
                type: "cuboid",
                children: [],
                opacity: 1,
                translateX: -2,
                translateY: 44,
                translateZ: -24,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: -53,
                rotateY: -27,
                rotateZ: 0,
                width: 7,
                height: 76,
                depth: 10,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "c78888b4-4142-4215-ba84-92db5c668a74",
                name: "finger",
                type: "cuboid",
                children: [],
                opacity: 1,
                translateX: -15,
                translateY: 44,
                translateZ: -9,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: -53,
                rotateY: 9,
                rotateZ: 37,
                width: 7,
                height: 49,
                depth: 10,
                radius: 200,
                baseSides: 3,
              },
              {
                id: "3e86031f-1334-441f-a051-27982d426c41",
                name: "finger ",
                type: "cuboid",
                children: [],
                opacity: 1,
                translateX: 8,
                translateY: 17,
                translateZ: 14,
                scaleX: 1,
                scaleY: 1,
                scaleZ: 1,
                rotateX: 59,
                rotateY: -27,
                rotateZ: -11,
                width: 7,
                height: 34,
                depth: 10,
                radius: 200,
                baseSides: 3,
              },
            ],
            opacity: 1,
            translateX: 1,
            translateY: 79,
            translateZ: 40,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            rotateX: 78,
            rotateY: 0,
            rotateZ: 0,
            width: 13,
            height: 100,
            depth: 13,
            radius: 200,
            baseSides: 3,
          },
        ],
        color: "#71480e",
        opacity: 1,
        translateX: 0,
        translateY: -150,
        translateZ: 225,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: 11,
        rotateY: -4,
        rotateZ: 180,
        width: 16,
        height: 150,
        depth: 12,
        radius: 200,
        baseSides: 3,
      },
    ],
    color: "#f0feff",
    opacity: 1,
    translateX: 500,
    translateY: 500,
    translateZ: 100,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 200,
    height: 200,
    depth: 200,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "9516dc21-2897-466d-b922-468ad92c82e7",
    name: "snowflake",
    collapsed: true,
    type: "cuboid",
    children: [
      {
        id: "9d9a93f2-9e59-4777-bc99-cd4ced89bdb4",
        name: "crystal",
        type: "cuboid",
        children: [],
        opacity: 1,
        translateX: 0,
        translateY: 0,
        translateZ: 0,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: 60,
        rotateY: 0,
        rotateZ: 0,
        width: 10,
        height: 10,
        depth: 50,
        radius: 200,
        baseSides: 3,
      },
      {
        id: "e336820e-33b7-4aec-adc8-a4480bf05497",
        name: "crystal",
        type: "cuboid",
        children: [],
        opacity: 1,
        translateX: 0,
        translateY: 0,
        translateZ: 0,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: -60,
        rotateY: 0,
        rotateZ: 0,
        width: 10,
        height: 10,
        depth: 50,
        radius: 200,
        baseSides: 3,
      },
    ],
    color: "#f0feff",
    opacity: 1,
    translateX: 403,
    translateY: 862,
    translateZ: 429,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 10,
    height: 10,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "5b391bd1-6170-4b50-9427-48df6d943e09",
    name: "snowflake instance",
    instanceOf: "9516dc21-2897-466d-b922-468ad92c82e7",
    type: "cuboid",
    collapsed: true,
    children: [],
    color: "#f0feff",
    opacity: 1,
    translateX: 800,
    translateY: 400,
    translateZ: 300,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 10,
    height: 10,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "373f55d6-ef22-4428-87f6-42617bf18152",
    name: "snowflake instance",
    instanceOf: "9516dc21-2897-466d-b922-468ad92c82e7",
    type: "cuboid",
    collapsed: true,
    children: [],
    color: "#f0feff",
    opacity: 1,
    translateX: 871,
    translateY: 591,
    translateZ: 424,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 10,
    height: 10,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "d0f16324-7e01-4cb0-838d-53f9b94f455b",
    name: "snowflake instance",
    instanceOf: "9516dc21-2897-466d-b922-468ad92c82e7",
    type: "cuboid",
    collapsed: true,
    children: [],
    color: "#f0feff",
    opacity: 1,
    translateX: 800,
    translateY: 800,
    translateZ: 100,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 10,
    height: 10,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "e8a56abf-5a6d-471e-a16c-338655191c43",
    name: "snowflake instance",
    instanceOf: "9516dc21-2897-466d-b922-468ad92c82e7",
    collapsed: true,
    type: "cuboid",
    children: [],
    color: "#f0feff",
    opacity: 1,
    translateX: 300,
    translateY: 500,
    translateZ: 585,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 10,
    height: 10,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "ab9f08aa-2736-4eb2-a882-39c02c51744d",
    name: "snowflake instance",
    instanceOf: "9516dc21-2897-466d-b922-468ad92c82e7",
    collapsed: true,
    type: "cuboid",
    children: [],
    color: "#f0feff",
    opacity: 1,
    translateX: 200,
    translateY: 700,
    translateZ: 200,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 10,
    height: 10,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "cf2a0b46-8e6f-4144-b4e6-2575585170f4",
    name: "snowflake instance",
    instanceOf: "9516dc21-2897-466d-b922-468ad92c82e7",
    collapsed: true,
    type: "cuboid",
    children: [],
    color: "#f0feff",
    opacity: 1,
    translateX: 128,
    translateY: 407,
    translateZ: 284,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 10,
    height: 10,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "92488363-77fc-40ea-9c87-2e8a8fb3bf7a",
    name: "snowflake instance",
    instanceOf: "9516dc21-2897-466d-b922-468ad92c82e7",
    collapsed: true,
    type: "cuboid",
    children: [],
    color: "#f0feff",
    opacity: 1,
    translateX: 100,
    translateY: 100,
    translateZ: 30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 10,
    height: 10,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "d91001f1-cd45-44b6-be1e-97e85ecf0215",
    name: "snowflake instance",
    instanceOf: "9516dc21-2897-466d-b922-468ad92c82e7",
    type: "cuboid",
    collapsed: true,
    children: [],
    color: "#f0feff",
    opacity: 1,
    translateX: 500,
    translateY: 130,
    translateZ: 194,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 90,
    width: 10,
    height: 10,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
  {
    id: "29b3f392-92e6-4d1c-b543-ae4fba12c522",
    name: "ground",
    type: "cuboid",
    children: [],
    color: "#f0feff",
    opacity: 1,
    translateX: 500,
    translateY: 500,
    translateZ: -25,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
    width: 1000,
    height: 1000,
    depth: 50,
    radius: 200,
    baseSides: 3,
  },
];
