import type { Node } from "../App";

export const starDestroyer: Node = {
  id: "oq348n75tfw8b5c476f5tdw784",
  name: "Star Destroyer",
  type: "group",
  color: "#b0b0b0",
  opacity: 1,
  translateX: 500,
  translateY: 565,
  translateZ: 260,
  scaleX: 1,
  scaleY: 1,
  scaleZ: 1,
  rotateX: 0,
  rotateY: 0,
  rotateZ: 180,
  width: 0,
  height: 0,
  depth: 0,
  radius: 0,
  baseSides: 0,
  borderColor: undefined,
  children: [
    {
      id: "bfea947f-8da9-45ac-ac95-6fc605938f94",
      name: "top hull",
      type: "pyramid",
      children: [
        {
          id: "9fa6fbe1-5864-49fe-9af2-a93a3e18161f",
          name: "back top left",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: 27,
          translateY: 54,
          translateZ: -244,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 100,
          rotateY: -44.5,
          rotateZ: 0,
          width: 200,
          height: 13,
          depth: 200,
          radius: 87,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "7a403dff-54a4-451f-a926-ca2038a2d117",
          name: "back top right",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: -27,
          translateY: 54,
          translateZ: -244,
          scaleX: -1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 100,
          rotateY: 44.5,
          rotateZ: 0,
          width: 200,
          height: 13,
          depth: 200,
          radius: 87,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "a44c444e-41e2-4755-aa8e-462d1371a538",
          name: "superstrucutre",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 34,
          translateZ: -190,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 30,
          width: 200,
          height: 143,
          depth: 200,
          radius: 39,
          baseSides: 6,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "7d4df908-55fe-499f-acd8-d6287d46660d",
          name: "superstrucutre level 2",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 59,
          translateZ: -205,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 30,
          width: 200,
          height: 115,
          depth: 200,
          radius: 27,
          baseSides: 6,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "e22002fe-f98e-4c37-9ef1-ab739eb84247",
          name: "superstrucutre level 3",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 82,
          translateZ: -233,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 30,
          width: 200,
          height: 79,
          depth: 200,
          radius: 20,
          baseSides: 6,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "599a92de-d140-43fe-b39f-71c9fa7133b0",
          name: "neck",
          type: "cuboid",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 111,
          translateZ: -246,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 12,
          height: 76,
          depth: 70,
          radius: 200,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "801a8882-821e-499e-a980-a00450385aa9",
          name: "spine",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 112,
          translateZ: -281,
          scaleX: 1,
          scaleY: 1.04,
          scaleZ: 1,
          rotateX: 90,
          rotateY: 90,
          rotateZ: 0,
          width: 200,
          height: 12,
          depth: 200,
          radius: 37,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "7d7bf3a3-f194-4536-aef6-b24466245632",
          name: "bridge",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 135,
          translateZ: -208,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 30,
          width: 200,
          height: 55,
          depth: 200,
          radius: 20,
          baseSides: 6,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "70da45a4-2f41-41b5-b9ea-53cb4981e7fe",
          name: "bridge",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 134,
          translateZ: -205,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 30,
          width: 200,
          height: 55,
          depth: 200,
          radius: 16,
          baseSides: 6,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "21124fe4-e912-48ec-8307-988b690cb854",
          name: "sensor",
          type: "sphere",
          children: [],
          opacity: 1,
          translateX: 15,
          translateY: 155,
          translateZ: -204,
          scaleX: 0.33,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 200,
          depth: 200,
          radius: 12,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "181e6ba0-277a-4995-8196-91187132bafd",
          name: "sensor",
          type: "sphere",
          children: [],
          opacity: 1,
          translateX: -15,
          translateY: 155,
          translateZ: -204,
          scaleX: 0.33,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 200,
          depth: 200,
          radius: 12,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "973c694b-e233-4a4a-89da-c59ba0029afc",
          name: "superstrucutre front",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 43,
          translateZ: -162,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 30,
          width: 200,
          height: 143,
          depth: 200,
          radius: 24,
          baseSides: 6,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "6a2260c9-2188-4f86-b087-85aabdb0c14f",
          name: "mast",
          type: "cuboid",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 163,
          translateZ: -212,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 12,
          height: 3,
          depth: 20,
          radius: 200,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "de8c6c42-7657-4606-a8ff-eb8d9071a833",
          name: "mast",
          type: "cuboid",
          children: [],
          opacity: 1,
          translateX: 0,
          translateY: 157,
          translateZ: -211,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 5,
          height: 3,
          depth: 20,
          radius: 200,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
      ],
      color: "#b0b0b0",
      opacity: 1,
      translateX: 0,
      translateY: 0,
      translateZ: 0,
      scaleX: 3,
      scaleY: 1,
      scaleZ: 1,
      rotateX: 90,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 512,
      depth: 200,
      radius: 92,
      baseSides: 4,
      borderColor: undefined,
    },
    {
      id: "9c43cbf7-181b-4513-9d8a-d22f80b8ef9b",
      name: "Engine",
      type: "prism",
      children: [
        {
          id: "d10ccbde-cacd-4f85-bd28-c41317812e1c",
          name: "thrust",
          type: "prism",
          children: [],
          color: "#47d1ff",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: -19,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 5,
          depth: 200,
          radius: 30,
          baseSides: 12,
          borderColor: undefined,
        },
      ],
      color: "#b0b0b0",
      opacity: 1,
      translateX: 0,
      translateY: 256,
      translateZ: -3,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
      rotateX: 90,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 38,
      depth: 200,
      radius: 36,
      baseSides: 12,
      borderColor: undefined,
    },
    {
      id: "c0a86c86-2166-4db2-95df-ebe650d2463d",
      name: "Engine clone",
      type: "prism",
      children: [
        {
          id: "989a6976-a98e-4ac6-a75f-fd2e2b6e2bf8",
          name: "thrust",
          type: "prism",
          children: [],
          color: "#47d1ff",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: -19,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 5,
          depth: 200,
          radius: 30,
          baseSides: 12,
          borderColor: undefined,
        },
      ],
      color: "#b0b0b0",
      opacity: 1,
      translateX: 115,
      translateY: 256,
      translateZ: -3,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
      rotateX: 90,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 38,
      depth: 200,
      radius: 36,
      baseSides: 12,
      borderColor: undefined,
    },
    {
      id: "9a356537-882d-45e5-8904-9eba320b2a12",
      name: "Engine clone",
      type: "prism",
      children: [
        {
          id: "52042f18-2eaa-4899-80b4-3f7c3bd9aa66",
          name: "thrust",
          type: "prism",
          children: [],
          color: "#47d1ff",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: -19,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 5,
          depth: 200,
          radius: 30,
          baseSides: 12,
          borderColor: undefined,
        },
      ],
      color: "#b0b0b0",
      opacity: 1,
      translateX: -125,
      translateY: 256,
      translateZ: -3,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
      rotateX: 90,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 38,
      depth: 200,
      radius: 36,
      baseSides: 12,
      borderColor: undefined,
    },
    {
      id: "c3b922e5-674b-4799-92fe-d72570dc9bbd",
      name: "small engine",
      type: "prism",
      children: [
        {
          id: "48043b4f-c888-49be-bd56-57750d84ed82",
          name: "thrust",
          type: "prism",
          children: [],
          color: "#47d1ff",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: -19,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 5,
          depth: 200,
          radius: 30,
          baseSides: 12,
          borderColor: undefined,
        },
      ],
      color: "#b0b0b0",
      opacity: 1,
      translateX: -58,
      translateY: 247,
      translateZ: -36,
      scaleX: 0.6,
      scaleY: 0.6,
      scaleZ: 1,
      rotateX: 90,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 38,
      depth: 200,
      radius: 36,
      baseSides: 12,
      borderColor: undefined,
    },
    {
      id: "c0f5f067-efd4-4776-9e24-45fbbff0d4b6",
      name: "small engine",
      type: "prism",
      children: [
        {
          id: "72c97a09-db7a-4a5e-910b-9700d4c2e1a4",
          name: "thrust",
          type: "prism",
          children: [],
          color: "#47d1ff",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: -19,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 5,
          depth: 200,
          radius: 30,
          baseSides: 12,
          borderColor: undefined,
        },
      ],
      color: "#b0b0b0",
      opacity: 1,
      translateX: -58,
      translateY: 247,
      translateZ: 29,
      scaleX: 0.6,
      scaleY: 0.6,
      scaleZ: 1,
      rotateX: 90,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 38,
      depth: 200,
      radius: 36,
      baseSides: 12,
      borderColor: undefined,
    },
    {
      id: "259a19a1-bb36-44cd-8ca4-3df2bf51fea0",
      name: "small engine ",
      type: "prism",
      children: [
        {
          id: "b5fb8ad9-de90-4c4a-ac80-7e8a5ec46ee4",
          name: "thrust",
          type: "prism",
          children: [],
          color: "#47d1ff",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: -19,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 5,
          depth: 200,
          radius: 30,
          baseSides: 12,
          borderColor: undefined,
        },
      ],
      color: "#b0b0b0",
      opacity: 1,
      translateX: 58,
      translateY: 247,
      translateZ: 29,
      scaleX: 0.6,
      scaleY: 0.6,
      scaleZ: 1,
      rotateX: 90,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 38,
      depth: 200,
      radius: 36,
      baseSides: 12,
      borderColor: undefined,
    },
    {
      id: "a5bbac75-886f-4d97-94be-94ffaff55910",
      name: "small engine",
      type: "prism",
      children: [
        {
          id: "472faf2f-033c-4114-86b9-60b84da92774",
          name: "thrust",
          type: "prism",
          children: [],
          color: "#47d1ff",
          opacity: 1,
          translateX: 0,
          translateY: 0,
          translateZ: -19,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 0,
          rotateY: 0,
          rotateZ: 0,
          width: 200,
          height: 5,
          depth: 200,
          radius: 30,
          baseSides: 12,
          borderColor: undefined,
        },
      ],
      color: "#b0b0b0",
      opacity: 1,
      translateX: 58,
      translateY: 247,
      translateZ: -36,
      scaleX: 0.6,
      scaleY: 0.6,
      scaleZ: 1,
      rotateX: 90,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 38,
      depth: 200,
      radius: 36,
      baseSides: 12,
      borderColor: undefined,
    },
    {
      id: "5e6833bd-cf21-4c42-8de9-f1f3196905cc",
      name: "bottom hull",
      type: "pyramid",
      children: [
        {
          id: "504ac9a6-2b16-4f94-91eb-4c4abe38f072",
          name: "back bottom right",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: 27,
          translateY: 54,
          translateZ: -244,
          scaleX: 1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 100,
          rotateY: -44.5,
          rotateZ: 0,
          width: 200,
          height: 13,
          depth: 200,
          radius: 87,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
        {
          id: "c702a339-6b32-42e7-ae54-86102731d2ad",
          name: "back bottom left",
          type: "prism",
          children: [],
          opacity: 1,
          translateX: -27,
          translateY: 54,
          translateZ: -244,
          scaleX: -1,
          scaleY: 1,
          scaleZ: 1,
          rotateX: 100,
          rotateY: 44.5,
          rotateZ: 0,
          width: 200,
          height: 13,
          depth: 200,
          radius: 87,
          baseSides: 3,
          color: undefined,
          borderColor: undefined,
        },
      ],
      color: "#b0b0b0",
      opacity: 1,
      translateX: 0,
      translateY: 0,
      translateZ: -8,
      scaleX: 3,
      scaleY: 1,
      scaleZ: 1,
      rotateX: 90,
      rotateY: 0,
      rotateZ: 180,
      width: 200,
      height: 512,
      depth: 200,
      radius: 92,
      baseSides: 4,
      borderColor: undefined,
    },
    {
      id: "bb3d3c1c-9292-4164-ac36-5db415368e2e",
      name: "bottom sensor",
      type: "sphere",
      children: [],
      color: "#b0b0b0",
      opacity: 1,
      translateX: 0,
      translateY: 155,
      translateZ: -47,
      scaleX: 1,
      scaleY: 1,
      scaleZ: 1,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      width: 200,
      height: 200,
      depth: 200,
      radius: 52,
      baseSides: 3,
      borderColor: undefined,
    },
  ],
};
