import type { Node } from "./App";

export const defaultModel: Node[] = [
  {
    id: "257498b0-cb4d-4cb7-896c-e55b1c19c643",
    name: "head",
    type: "sphere",
    children: [
      {
        id: "946da4b3-c089-4890-bb9b-e767e93bacf4",
        name: "ears",
        type: "rectPrism",
        children: [],
        opacity: 1,
        translateX: 0,
        translateY: 0,
        translateZ: 0,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        width: 384,
        height: 100,
        depth: 100,
        radius: 200,
        borderColor: undefined,
        color: undefined,
      },
      {
        id: "9c500404-f97a-4905-b4d9-1c22d5694293",
        name: "left eye",
        type: "sphere",
        children: [],
        color: "#00ddff",
        opacity: 1,
        translateX: -90,
        translateY: 150,
        translateZ: 10,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        width: 200,
        height: 200,
        depth: 200,
        radius: 20,
        borderColor: undefined,
      },
      {
        id: "867acc6b-54bc-4693-af49-259887e17d40",
        name: "right eye",
        type: "sphere",
        children: [],
        color: "#00ddff",
        opacity: 1,
        translateX: 90,
        translateY: 150,
        translateZ: 10,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        width: 200,
        height: 200,
        depth: 200,
        radius: 20,
        borderColor: undefined,
      },
      {
        id: "ef498a28-3d81-4fd6-85eb-f023186de5be",
        name: "nose",
        type: "sphere",
        children: [],
        opacity: 1,
        translateX: 0,
        translateY: 143,
        translateZ: -28,
        scaleX: 1,
        scaleY: 2.78,
        scaleZ: 1.3,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        width: 200,
        height: 200,
        depth: 200,
        radius: 40,
        borderColor: undefined,
        color: undefined,
      },
      {
        id: "c547e1b2-076f-4b1e-b5ba-5affec08a904",
        name: "hair",
        type: "sphere",
        children: [],
        color: "#000000",
        opacity: 1,
        translateX: 0,
        translateY: -31,
        translateZ: 35,
        scaleX: 1,
        scaleY: 1.02,
        scaleZ: 1,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        width: 200,
        height: 200,
        depth: 200,
        borderColor: undefined,
        radius: 200,
      },
      {
        id: "546c2cc9-1232-4bdc-850c-f53d464d1fae",
        name: "mouth",
        type: "rectPrism",
        children: [
          {
            id: "9b61265d-77f8-4b47-9a72-6f87fc6e35e8",
            name: "teeth",
            type: "rectPrism",
            children: [],
            color: "#ffffff",
            opacity: 1,
            translateX: 0,
            translateY: 7,
            translateZ: 22,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            rotateX: 30,
            rotateY: 0,
            rotateZ: 0,
            width: 150,
            height: 27,
            depth: 22,
            radius: 200,
            borderColor: undefined,
          },
        ],
        color: "#bd0000",
        opacity: 1,
        translateX: 0,
        translateY: 125,
        translateZ: -98,
        scaleX: 1,
        scaleY: 1,
        scaleZ: 1,
        rotateX: -40,
        rotateY: 0,
        rotateZ: 0,
        width: 150,
        height: 39,
        depth: 53,
        radius: 200,
        borderColor: undefined,
      },
    ],
    color: "#ff6bf3",
    borderColor: "#000000",
    opacity: 1,
    translateX: 500,
    translateY: 500,
    translateZ: 400,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
    width: 200,
    height: 200,
    depth: 200,
    radius: 200,
  },
];
